name: CI
on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47
        with:
          ruby-version: '3.2.1'
      - name: Install dependencies
        run: bundle install
      - name: Build
        run: bundle exec jekyll build