name: CI
on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
        with:
          ruby-version: '3.2.1'
      - name: Install dependencies
        run: bundle install
      - name: Build
        run: bundle exec jekyll build